# Generated by Django 5.2.12 on 2026-04-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='descritption',
            new_name='description',
        ),
    ]
