# Generated by Django 5.2.12 on 2026-04-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_descritption_searchhistory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
